version: '3.3'
services:
  db:
    image: biarms/mysql:5.7
    restart: always
    volumes:
      - ./build/data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'demodb'
      MYSQL_USER: 'demouser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'