spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: demouser
    password: password
    url: jdbc:mysql://localhost:3306/demodb?autoReconnect=true&useSSL=false
    hikari:
      password: ${spring.datasource.password}
      username: ${spring.datasource.username}
      driver-class-name: ${spring.datasource.driver-class-name}
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

management:
  endpoints:
    web:
      exposure:
        include: "*"