CREATE TABLE USERS (ID INT AUTO_INCREMENT PRIMARY KEY, EMAIL VARCHAR(45));
INSERT INTO USERS (ID, EMAIL) VALUES (1, 'johndoe@gmail.com');
INSERT INTO USERS (ID, EMAIL) VALUES (2, 'janedoe@gmail.com');
